version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ponder_dev
    ports:
      - "6432:6432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 6432
volumes:
  postgres_data: 